### ISSUE TITLE
check_disk_io_ucd.pl dev

### ISSUE THREAD

**Issue by gabrielfsousa** [tart/tart-monitoring#2]
hello

i cant get the dev name to work :(

 --- Physical volume ---
  PV Name               /dev/hda2
  VG Name               VolGroup00
  PV Size               59.90 GB / not usable 22.10 MB
  Allocatable           yes (but full)
  PE Size (KByte)       32768
  Total PE              1916
  Free PE               0
  Allocated PE          1916
  PV UUID               blV2qd-nNuW-zFMD-0Mo1-0y0E-CxU4-9X9AsY

tried hda , hda2, /dev/hda, /dev/hda2 , VolGroup00 no go,
what i'm doing wrong ?

**Comment by mertcetin** [comment]
Hi,
hda should work.

Example usage is:
./check_disk_io_ucd.pl -H $HOSTADDRESS$ -C nagios -s 2 -d sda -w 1000 -c 3000

**Comment by hasegeli** [comment]
This script is from Herbert Stadler (hestadler@gmx.at).  It was just copied to here.  You can try reporting any problem to them.
