### ISSUE TITLE
CheckMySQLTableStatus table filter only works for perfdata

### ISSUE THREAD

**Issue by mamunga** [tart/tart-monitoring#3]
The "-t" parameter only filters for performance data output.
The OutputUpperLimit class checks ALL tables for warning/critical status, but there is no filtering later.
Because of this, all tables that are in warning/critical state - according to the input w/c limits - would affect the plugin return code, not just the ones in the "-t" parameter.

Example:
`./checkMySQLTableStatus.py -H $HOSTNAME -P $PORT -t Schema1.Table1 -m rows,data_length -u $USER -p $PASSWORD -w 100G,100000000 -c 1000G,300000000`

Output:
```
CheckMySQLTableStatus warning: Schema1.Table2.data_length = 281M reached 100M; | Schema1.Table1.rows=4695;100000000000;1000000000000;0; Schema1.Table1.data_length=2146304;100000000;300000000;0;
return code: 1
```

Expected:
```
CheckMySQLTableStatus ok | Schema1.Table1.rows=4695;100000000000;1000000000000;0; Schema1.Table1.data_length=2146304;100000000;300000000;0;
return code: 0
```

**Comment by hasegeli** [comment]
I am sorry for late response.  This organisation is pretty much dead.  I copied this script to the current repository I am working on, and fixed the problem in there:

https://github.com/innogames/igmonplugins/blob/master/src/check_mysql_table_status.py

Feel free to create issues there.
